name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: rustup target add arm-unknown-linux-musleabi
#    - run: cargo check 
    - run: apt-get install g++-arm-linux-musleabi
    - run: cargo build  
    - run: cargo test
